name: Sync with Hugging Face Space

on:
  push:
    branches: [main] # لو البرانش بتاعك اسمه master غيريها

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Push to Hugging Face
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        # بنستخدم force عشان دايماً جيت هب يمسح أي لخبطة قديمة على السبيس ويحط الكود النضيف
        run: git push --force https://Gogzzz:$HF_TOKEN@huggingface.co/spaces/Gogzzz/GearUp_AI main